config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :articles
=begin
  get "/articles"
  post "/articles"
  delete "/articles/:id" destroy
  get "/articles/:id"
  get "/articles/new"
  get "/articles/:id/" edit
  patch "/articles/:id"
  put "/articles/:id"
=end

  #get 'welcome/index'
  root 'welcome#index'

  #get "special", to: "welcome#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence:true, uniqueness: true
  validates :body, presence:true, length: { minimum: 20 }
  before_create :set_visits_count

  def update_visits_count
    self.update(visits_count: self.visits_count + 1)

  end

  private
  def set_visits_count
    self.visits_count = 0
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  #before_action :validate_user, except: [:show,:index]
  before_action :authenticate_user!, only: [:create, :new]
  before_action :set_article, except: [:index, :new, :create]

  #Get /articles
  def index
    #Obtiene los registros
    @articles = Article.all
  end
  #Get /articles/:id
  def show
    #Encontrar registro por id
    #@article = Article.find(params[:id])
    @article.update_visits_count
  end
  #Get /articles/new
  def new
    @article = Article.new
  end

  def edit

  end

  #POST /articles
  def create
  @article = current_user.articles.new(article_params)
    if @article.save
      redirect_to @article
    else
      render :new
    end
  end
  def destroy

    @article.destroy
    redirect_to articles_path
  end

  #PUT /articles/:id
  def update

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
    #@article.update_attributes({title: 'Nuevo Titulo'})
  end

  private
  def set_article
    @article = Article.find(params[:id])
  end

  def validate_user
    redirect_to new_user_session_path, notice: "Necesitas iniciar sesion"
  end

  def article_params
    params.require(:article).permit(:title,:body)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% @article.errors.full_messages.each do |message| %>
    <div class="bg-info text-white m-20">
      * <%= message %>
    </div>
  <%end%>

  <div class="field">
    <%= f.text_field :title, placeholder: "Titulo", class: "form-control"%>
  </div>
  <div class="field">
    <%= f.text_area :body, placeholder: "Escribe acá el articulo", style:"height:250px", class: "form-control"%>
  </div>
  <div class="field">
    <%= f.submit "Guardar", class:"btn btn-primary"%>
  </div>
<%end%>

app/views/articles/edit.html.erb
<div style="width:80%; margin:0 auto;">
  <h1>Editar articulo</h1>
  <%= render "form" %>
</div>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
  <div class="container">
    <h1> <%= link_to article.title, article, class:"verArticulo"%> </h1>
    <%= article.body %> - <%= link_to "Eliminar", article, method: :delete, class:"text-danger" %>
  </div>
<% end %>

app/views/articles/new.html.erb
<div style="width:80%; margin:0 auto;">
  <h1>Crear articulo</h1>
  <%= render "form" %>
</div>

app/views/articles/show.html.erb
<div class="container">
  <h1> <%= @article.title %> </h1>
  <% unless @article.user.nil?%>
    <p>
      Escrito por: <%= @article.user.email %>
    </p>
  <% end %>

  <% unless @article.visits_count.nil?%>
    <p>
      Visitas: <%= @article.visits_count %>
    </p>
  <% end %>

  <div>
    <%= @article.body %>
  </div>
  <div>

    <%= link_to "Editar", edit_article_path(@article), class:"btn btn-warning btn-sm" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
          <%= render "partials/navigation" %>
          <%= yield %>
          <!-- Flash messages -->
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/partials/_navigation.html.erb
<header class="container-fluid">
  <nav class="row menu d-flex justify-content-between align-items-center">
    <div class="logo col-md">
      <a href="#">
        <h1>Blogito</h1>
      </a>
    </div>
    <a class="col-md" href="">
      Inicio
    </a>
    <a class="col-md" href="">Diseño</a>
    <a class="col-md" href="">Programacion</a>
    <a class="col-md" href="">Tecnologia</a>
    <%if user_signed_in? %>
      <div class="col-md">
        <%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete, class:"text-warning"%>
      </div>
    <%else%>
      <div class="col-md">
        <%= link_to "Iniciar Sesión", new_user_session_path, class:"text-warning"%>
      </div>
      <div class="col-md">
        <%= link_to "Crear Cuenta", new_user_registration_path, class:"text-warning"%>
      </div>
    <%end %>
  </nav>
</header>

app/views/welcome/index.html.erb
<%if user_signed_in? %>

<div class="container">
  <div class="row">
    <div class="col-md-6">
    <h3>Bienvenido <%= current_user.email %> </h3>
    </div>
  </div>
</div>
<%end %>